extends: default

rules:
  # IaC repos usually don't require '---' at top
  document-start: disable

  # Grafana provisioning etc. often start with a blank line after templating/formatting
  empty-lines: disable

  # Don't error on line length; keep as warning
  line-length:
    max: 160
    level: warning

  indentation:
    spaces: 2
    indent-sequences: consistent

  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]

  comments:
    min-spaces-from-content: 1
